---
abstract: "replacement for C<< if ($foo eq 'bar') >>"
author:
  - 'Jason M. Mills <jmmills@cpan.org>'
build_requires:
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.017, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Object-Enum
requires:
  Class::Accessor::Fast: '0'
  Class::Data::Inheritable: '0'
  Sub::Exporter: '0'
  Sub::Install: '0'
version: '0.073'
